language: node_js
node_js:
  - "8"
before_install:
  - npm install -g lerna
install:
  - lerna bootstrap --hoist
script:
  - lerna run test
deploy:
  - lerna publish --canary=ci --cd-version=prerelease --yes
